name: Build and Deploy MESλREDUX to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write   # Needed to push to build
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1"
          bundler-cache: true
          cache-version: 0

      - name: Build Jekyll site
        env:
          JEKYLL_ENV: production
        run: bundle exec jekyll build --destination ./_site

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Notify Discord of deployment
        if: always()
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          title: "MESλREDUX Deployment"
          color: ${{ job.status == 'success' && '0xFF4500' || '0xFF0000' }}
          description: ${{ job.status == 'success' && 'MESλREDUX has been built and deployed successfully! See changes at https://mesaredux.mesagrey.ca' || 'The deployment failed! Check the workflow logs for details.' }}
          
      - name: Push built site to build branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git fetch origin build || echo "No remote build branch yet"

          # Create or switch to the build branch locally
          if git rev-parse --verify origin/build >/dev/null 2>&1; then
            git checkout build
            git merge -X ours origin/build --allow-unrelated-histories || true
          else
            git checkout --orphan build
          fi

          # Replace contents with the new site
          mkdir /tmp/keep_temp
          mv _site /tmp/keep_temp
          rm -rf ./*
          cp -r /tmp/keep_temp/_site/* ./
          rm -rf /tmp/keep_temp .bundle

          # Commit and push
          git add -A
          git commit -m "Built site from main branch" || echo "No changes to commit"
          git push origin build

